force-app/main/default/objects/Contact_Category__c/Contact_Category__c.object-meta.xml
<CustomObject>
    <label>Contact_Category</label>
    <nameField>
        <label>Contact_Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts_Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Category__c/fields/Categories__c.field-meta.xml
<CustomField>
    <fullName>Categories__c</fullName>
    <label>Categories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Tech</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Regulatory</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Wellbeing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Unsubscribe.cls
@RestResource(urlMapping='/unsubscribe/*')
global with sharing class Unsubscribe {    
@HttpPatch
        global static void unsubscribeFromTopic(String email, String topic) {
            List <Contact_Category__c> contatCategories = 
                [SELECT Categories__c, email__c FROM Contact_Category__c 
                 where Categories__c includes(:topic) AND email__c =:String.escapeSingleQuotes(email)];
            for(Contact_Category__c contactCategory : contatCategories) {
                    List<String> topics = contactCategory.Categories__c.split(';');
                    if(topics.contains(topic)){
                        topics.remove(topics.indexOf(topic));
                    }
                    contactCategory.Categories__c = String.join(topics,';');
               }
            update contatCategories;
        }
}