force-app/main/default/objects/Contact_Category__c/Contact_Category__c.object-meta.xml
<CustomObject>
    <label>Contact_Category</label>
    <nameField>
        <label>Contact_Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts_Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Category__c/fields/Categories__c.field-meta.xml
<CustomField>
    <fullName>Categories__c</fullName>
    <label>Categories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer</fullName>
            </value>
            <value>
                <fullName>Tech</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Regulatory</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Wellbeing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UnsubscribeTest.cls
@isTest(SeeAllData=false)
public class UnsubscribeTest {
    
    @isTest
    static void testPatchUnsubscribe() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/unsubscribe';
        req.httpMethod = 'PATCH';
        String contactEmail = 'aa@test.com';
        String topic = 'Business';
        //req.addParameter('customerId', 'AzizId');
        RestContext.request = req;
        RestContext.response = res;
        generateMockData();
        Test.startTest();
        Unsubscribe.unsubscribeFromTopic(contactEmail, topic);
        Test.stopTest();
        Contact_Category__c contactCategory = [SELECT Categories__c, email__c FROM Contact_Category__c where email__c=:contactEmail];
        System.assert(!contactCategory.Categories__c.split(';').contains(topic));
    }
    
    public static void generateMockData() {
        Contact_Category__c contactCategory = new Contact_Category__c();
        contactCategory.Categories__c = 'Volunteer;Tech;Business;Environment';
        contactCategory.email__c = 'aa@test.com';
        insert contactCategory;
    }
}